default_language_version:
  python: python3.10
exclude: |
  (?x)^(theme|cypress|\.github|moodle-training|deploy)$

repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
        types: [python]
        exclude_types: [javascript, jsx, ts, tsx]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "--errors-only",
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint_django", # Load an extension
            "--django-settings-module=project.settings",
          ]
