services:
    mapa-org-formularios:
      image: ${DOCKER_IMAGE:-nossas/mapa-org-formularios:latest}
      restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
      pull_policy: always
      # ports:
      #   - 80:8000
      environment:
        - DEBUG=${DEBUG:-True}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - DATABASE_URL=${DATABASE_URL}

      labels:
        - traefik.enable=true
        - traefik.http.services.mapa-org-formularios.loadbalancer.server.port=8000
        - traefik.http.routers.mapa-org-formularios.tls=true
        - traefik.http.routers.mapa-org-formularios.tls.certresolver=myresolver
        - traefik.http.routers.mapa-org-formularios.rule=Host(`${MSR_HOST}`,`${VOLUNTEER_HOST}` )

networks:
  default:
    name: bonde