name: Apply migrations

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
    tags:
      - v*
    paths:
      - "**/migrations/**"
  
  pull_request:
    branches:
      - "**"
    paths:
      - "**/migrations/**"

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment:
      name: ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'staging' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Check Python version
        run: python --version

      - name: Install prod requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: python manage.py migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
